/* The following code was generated by JFlex 1.6.1 */

package scanner.data;
import static scanner.data.Token.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/scanner/data/lexer.flex</tt>
 */
public class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\3\1\60\1\60\1\3\22\0\1\3\1\15\1\51"+
    "\1\4\1\0\1\15\1\6\1\57\1\4\1\4\1\14\1\12\1\4"+
    "\1\13\1\11\1\15\12\2\1\4\1\4\1\17\1\16\1\20\1\4"+
    "\1\0\1\56\3\1\1\53\6\1\1\52\5\1\1\55\1\1\1\54"+
    "\6\1\1\4\1\0\1\4\1\15\1\1\1\0\1\21\1\25\1\31"+
    "\1\36\1\27\1\37\1\43\1\33\1\35\1\1\1\30\1\40\1\41"+
    "\1\34\1\24\1\47\1\1\1\26\1\32\1\23\1\22\1\50\1\45"+
    "\1\42\1\46\1\44\1\7\1\5\1\10\1\4\6\0\1\60\u1fa2\0"+
    "\1\60\1\60\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\1\3\1\4\1\5\10\1\17\3\2\2"+
    "\1\4\17\3\2\6\6\3\2\0\30\3\2\0\16\3"+
    "\2\0\7\3\2\0\2\3\7\0\1\4";

  private static int [] zzUnpackAction() {
    int [] result = new int[117];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\142\0\223\0\61\0\61\0\304\0\365"+
    "\0\u0126\0\u0157\0\u0188\0\u01b9\0\u01ea\0\u021b\0\u024c\0\u027d"+
    "\0\u02ae\0\u02df\0\u0310\0\u0341\0\u0372\0\u03a3\0\u03d4\0\u0405"+
    "\0\u0436\0\u0467\0\u0498\0\u04c9\0\u04fa\0\u052b\0\u055c\0\u058d"+
    "\0\u05be\0\u05ef\0\u0620\0\u0651\0\u0682\0\u06b3\0\u06e4\0\u0715"+
    "\0\u0746\0\u0777\0\u07a8\0\u07d9\0\u080a\0\u083b\0\142\0\u086c"+
    "\0\u089d\0\u08ce\0\u08ff\0\u0930\0\u0961\0\u0992\0\u09c3\0\u09f4"+
    "\0\u0a25\0\u0a56\0\u0a87\0\u0ab8\0\u0ae9\0\u0b1a\0\u0b4b\0\u0b7c"+
    "\0\u0bad\0\u0bde\0\u0c0f\0\u0c40\0\u0c71\0\u0ca2\0\u0cd3\0\u0d04"+
    "\0\u0d35\0\u0d66\0\u0d97\0\u0dc8\0\u0df9\0\u0e2a\0\u0e5b\0\u0e8c"+
    "\0\u0ebd\0\u0eee\0\u0f1f\0\u0f50\0\u0f81\0\u0fb2\0\u0fe3\0\u1014"+
    "\0\u1045\0\u1076\0\u10a7\0\u10d8\0\u1109\0\u113a\0\u116b\0\u119c"+
    "\0\u11cd\0\u11fe\0\u122f\0\u1260\0\u1291\0\u12c2\0\u12f3\0\u1324"+
    "\0\u1355\0\u1386\0\u13b7\0\u13e8\0\u1419\0\u144a\0\u147b\0\u14ac"+
    "\0\u14dd\0\u150e\0\u153f\0\u1570\0\61";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[117];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\3\6"+
    "\1\11\1\12\3\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\3\1\21\1\22\1\23\1\3\1\24\1\25\2\3"+
    "\1\26\1\27\1\30\1\31\2\3\1\32\1\3\1\33"+
    "\2\3\1\34\1\35\5\3\1\36\63\0\2\3\16\0"+
    "\30\3\1\0\5\3\4\0\1\4\6\0\1\37\54\0"+
    "\1\6\10\0\1\6\50\0\1\6\7\0\1\6\54\0"+
    "\1\6\3\0\1\6\44\0\1\4\10\0\1\6\2\0"+
    "\1\6\60\0\1\6\60\0\1\6\1\13\57\0\1\6"+
    "\1\0\1\13\41\0\2\3\16\0\1\3\1\40\26\3"+
    "\1\0\5\3\3\0\2\3\16\0\13\3\1\41\14\3"+
    "\1\0\5\3\3\0\2\3\16\0\25\3\1\42\2\3"+
    "\1\0\5\3\3\0\2\3\16\0\5\3\1\43\22\3"+
    "\1\0\5\3\3\0\2\3\16\0\6\3\1\44\21\3"+
    "\1\0\5\3\3\0\2\3\16\0\13\3\1\45\3\3"+
    "\1\46\1\3\1\47\6\3\1\0\5\3\3\0\2\3"+
    "\16\0\1\46\2\3\1\50\6\3\1\51\15\3\1\0"+
    "\5\3\3\0\2\3\16\0\2\3\1\52\7\3\1\53"+
    "\1\3\1\54\7\3\1\55\3\3\1\0\5\3\3\0"+
    "\2\3\16\0\13\3\1\56\2\3\1\57\11\3\1\0"+
    "\5\3\3\0\2\3\16\0\3\3\1\60\2\3\1\61"+
    "\21\3\1\0\5\3\3\0\2\3\16\0\3\3\1\62"+
    "\13\3\1\63\10\3\1\0\5\3\3\0\2\3\16\0"+
    "\3\3\1\64\24\3\1\0\5\3\3\0\2\3\16\0"+
    "\3\3\1\40\24\3\1\0\5\3\3\0\2\3\16\0"+
    "\12\3\1\65\15\3\1\0\5\3\3\0\2\3\16\0"+
    "\3\3\1\66\24\3\1\0\5\3\11\0\1\67\60\0"+
    "\1\70\53\0\1\37\57\0\2\3\16\0\2\3\1\71"+
    "\25\3\1\0\5\3\3\0\2\3\16\0\11\3\1\72"+
    "\2\3\1\73\13\3\1\0\5\3\3\0\2\3\16\0"+
    "\26\3\1\74\1\3\1\0\5\3\3\0\2\3\16\0"+
    "\6\3\1\75\21\3\1\0\5\3\3\0\2\3\16\0"+
    "\2\3\1\76\17\3\1\77\5\3\1\0\5\3\3\0"+
    "\2\3\16\0\1\3\1\100\26\3\1\0\5\3\3\0"+
    "\2\3\16\0\11\3\1\101\16\3\1\0\5\3\3\0"+
    "\2\3\16\0\2\3\1\102\25\3\1\0\5\3\3\0"+
    "\2\3\16\0\13\3\1\103\14\3\1\0\5\3\3\0"+
    "\2\3\16\0\1\62\27\3\1\0\5\3\3\0\2\3"+
    "\16\0\1\104\4\3\1\105\22\3\1\0\5\3\3\0"+
    "\2\3\16\0\3\3\1\106\24\3\1\0\5\3\3\0"+
    "\2\3\16\0\22\3\1\107\1\110\4\3\1\0\5\3"+
    "\3\0\2\3\16\0\14\3\1\111\13\3\1\0\5\3"+
    "\3\0\2\3\16\0\2\3\1\57\25\3\1\0\5\3"+
    "\3\0\2\3\16\0\1\3\1\112\26\3\1\0\5\3"+
    "\3\0\2\3\16\0\16\3\1\113\11\3\1\0\5\3"+
    "\3\0\2\3\16\0\5\3\1\57\22\3\1\0\5\3"+
    "\3\0\2\3\16\0\3\3\1\114\24\3\1\0\5\3"+
    "\3\0\2\3\16\0\13\3\1\115\14\3\1\0\5\3"+
    "\3\0\2\3\16\0\14\3\1\116\13\3\1\0\5\3"+
    "\3\0\2\3\16\0\14\3\1\117\2\3\1\120\10\3"+
    "\1\0\5\3\54\0\1\121\60\0\1\122\7\0\2\3"+
    "\16\0\3\3\1\57\24\3\1\0\5\3\3\0\2\3"+
    "\16\0\14\3\1\123\13\3\1\0\5\3\3\0\2\3"+
    "\16\0\3\3\1\124\24\3\1\0\5\3\3\0\2\3"+
    "\16\0\6\3\1\125\21\3\1\0\5\3\3\0\2\3"+
    "\16\0\1\126\27\3\1\0\5\3\3\0\2\3\16\0"+
    "\1\3\1\127\26\3\1\0\5\3\3\0\2\3\16\0"+
    "\14\3\1\130\13\3\1\0\5\3\3\0\2\3\16\0"+
    "\20\3\1\57\7\3\1\0\5\3\3\0\2\3\16\0"+
    "\6\3\1\57\21\3\1\0\5\3\3\0\2\3\16\0"+
    "\6\3\1\127\21\3\1\0\5\3\3\0\2\3\16\0"+
    "\2\3\1\131\6\3\1\56\16\3\1\0\5\3\3\0"+
    "\2\3\16\0\2\3\1\132\25\3\1\0\5\3\3\0"+
    "\2\3\16\0\1\3\1\133\26\3\1\0\5\3\3\0"+
    "\2\3\16\0\5\3\1\56\22\3\1\0\5\3\3\0"+
    "\2\3\16\0\13\3\1\134\14\3\1\0\5\3\3\0"+
    "\2\3\16\0\6\3\1\135\21\3\1\0\5\3\3\0"+
    "\2\3\16\0\2\3\1\136\25\3\1\0\5\3\3\0"+
    "\2\3\16\0\4\3\1\116\23\3\1\0\5\3\3\0"+
    "\2\3\16\0\1\137\27\3\1\0\5\3\3\0\2\3"+
    "\16\0\1\56\27\3\1\0\5\3\3\0\2\3\16\0"+
    "\22\3\1\57\5\3\1\0\5\3\3\0\2\3\16\0"+
    "\17\3\1\101\10\3\1\0\5\3\3\0\2\3\16\0"+
    "\15\3\1\57\12\3\1\0\5\3\3\0\2\3\16\0"+
    "\1\140\27\3\1\0\5\3\55\0\1\141\60\0\1\142"+
    "\6\0\2\3\16\0\22\3\1\107\5\3\1\0\5\3"+
    "\3\0\2\3\16\0\13\3\1\57\14\3\1\0\5\3"+
    "\3\0\2\3\16\0\15\3\1\143\12\3\1\0\5\3"+
    "\3\0\2\3\16\0\7\3\1\57\20\3\1\0\5\3"+
    "\3\0\2\3\16\0\5\3\1\124\22\3\1\0\5\3"+
    "\3\0\2\3\16\0\11\3\1\144\16\3\1\0\5\3"+
    "\3\0\2\3\16\0\14\3\1\145\13\3\1\0\5\3"+
    "\3\0\2\3\16\0\14\3\1\146\13\3\1\0\5\3"+
    "\3\0\2\3\16\0\10\3\1\56\17\3\1\0\5\3"+
    "\3\0\2\3\16\0\6\3\1\117\21\3\1\0\5\3"+
    "\3\0\2\3\16\0\3\3\1\147\24\3\1\0\5\3"+
    "\3\0\2\3\16\0\10\3\1\150\17\3\1\0\5\3"+
    "\3\0\2\3\16\0\1\3\1\151\26\3\1\0\5\3"+
    "\3\0\2\3\16\0\2\3\1\65\25\3\1\0\5\3"+
    "\56\0\1\152\60\0\1\153\5\0\2\3\16\0\6\3"+
    "\1\147\21\3\1\0\5\3\3\0\2\3\16\0\2\3"+
    "\1\154\25\3\1\0\5\3\3\0\2\3\16\0\13\3"+
    "\1\155\14\3\1\0\5\3\3\0\2\3\16\0\10\3"+
    "\1\57\17\3\1\0\5\3\3\0\2\3\16\0\16\3"+
    "\1\57\11\3\1\0\5\3\3\0\2\3\16\0\12\3"+
    "\1\57\15\3\1\0\5\3\3\0\2\3\16\0\17\3"+
    "\1\56\10\3\1\0\5\3\57\0\1\156\60\0\1\157"+
    "\4\0\2\3\16\0\6\3\1\62\21\3\1\0\5\3"+
    "\3\0\2\3\16\0\1\3\1\101\26\3\1\0\5\3"+
    "\60\0\1\160\60\0\1\161\12\0\1\162\60\0\1\163"+
    "\64\0\1\164\123\0\1\165\52\0\1\165\7\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5537];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\2\1\2\11\60\1\2\0\30\1\2\0"+
    "\16\1\2\0\7\1\2\0\2\1\7\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[117];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
public String lexeme;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 198) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { lexeme=yytext(); return OPERADOR;
            }
          case 7: break;
          case 2: 
            { return ERROR;
            }
          case 8: break;
          case 3: 
            { lexeme=yytext(); return IDENTIFICADOR;
            }
          case 9: break;
          case 4: 
            { lexeme=yytext(); return LITERAL;
            }
          case 10: break;
          case 5: 
            { /*Ignore*/
            }
          case 11: break;
          case 6: 
            { lexeme=yytext(); return PALABRA_RESERVADA;
            }
          case 12: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
