/* The following code was generated by JFlex 1.6.1 */

package scanner.data;
import static scanner.data.Token.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/scanner/data/lexer.flex</tt>
 */
public class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\6\1\11\1\12\1\12\1\11\22\0\1\6\1\54\1\7"+
    "\1\20\1\0\1\54\1\52\1\13\1\50\1\50\1\54\1\53\1\50"+
    "\1\14\1\15\1\54\1\2\10\4\1\3\1\50\1\50\1\56\1\55"+
    "\1\57\1\50\1\0\6\5\21\1\1\17\2\1\1\50\1\10\1\50"+
    "\1\54\1\1\1\0\1\31\1\40\1\34\1\21\1\22\1\23\1\32"+
    "\1\42\1\24\1\1\1\41\1\26\1\27\1\25\1\36\1\46\1\1"+
    "\1\35\1\30\1\37\1\33\1\47\1\44\1\16\1\45\1\43\1\50"+
    "\1\51\1\50\1\50\6\0\1\12\u1fa2\0\1\12\1\12\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\1\3\2\4\1\5\2\2\3\1\17\3"+
    "\6\1\1\2\1\6\3\0\1\7\10\0\1\3\1\10"+
    "\5\3\1\10\17\3\1\11\1\12\1\7\1\13\4\0"+
    "\1\14\3\0\30\3\10\0\16\3\1\0\1\14\3\0"+
    "\7\3\2\0\2\3";

  private static int [] zzUnpackAction() {
    int [] result = new int[143];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\60\0\140\0\220\0\300\0\60\0\360\0\u0120"+
    "\0\u0150\0\60\0\u0180\0\u01b0\0\u01e0\0\u0210\0\u0240\0\u0270"+
    "\0\u02a0\0\u02d0\0\u0300\0\u0330\0\u0360\0\u0390\0\u03c0\0\u03f0"+
    "\0\u0420\0\u0450\0\u0480\0\u04b0\0\u04e0\0\u0510\0\u0540\0\u0570"+
    "\0\u05a0\0\u05d0\0\u0600\0\u0630\0\360\0\60\0\u0660\0\u0690"+
    "\0\u06c0\0\u06f0\0\u0720\0\u0750\0\u0780\0\u07b0\0\u07e0\0\u0810"+
    "\0\u0840\0\u0870\0\u08a0\0\u08d0\0\u0900\0\140\0\u0930\0\u0960"+
    "\0\u0990\0\u09c0\0\u09f0\0\u0a20\0\u0a50\0\u0a80\0\u0ab0\0\u0ae0"+
    "\0\u0b10\0\u0b40\0\u0b70\0\u0ba0\0\u0bd0\0\u0600\0\u0c00\0\360"+
    "\0\60\0\u0c30\0\u0c60\0\u0c90\0\u0cc0\0\u0cf0\0\u0d20\0\u0d50"+
    "\0\u0cf0\0\u0d80\0\u0db0\0\u0de0\0\u0e10\0\u0e40\0\u0e70\0\u0ea0"+
    "\0\u0ed0\0\u0f00\0\u0f30\0\u0f60\0\u0f90\0\u0fc0\0\u0ff0\0\u1020"+
    "\0\u1050\0\u1080\0\u10b0\0\u10e0\0\u1110\0\u1140\0\u1170\0\u11a0"+
    "\0\u11d0\0\u1200\0\u1230\0\u1260\0\u1290\0\u12c0\0\u12f0\0\u1320"+
    "\0\u1350\0\u1380\0\u13b0\0\u13e0\0\u1410\0\u1440\0\u1470\0\u14a0"+
    "\0\u14d0\0\u1500\0\u1530\0\u1560\0\u1590\0\u15c0\0\u15f0\0\u1620"+
    "\0\60\0\u1650\0\u1680\0\u16b0\0\u16e0\0\u1710\0\u1740\0\u1770"+
    "\0\u17a0\0\u17d0\0\u1800\0\u1830\0\u1860\0\u1890\0\u18c0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[143];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\2\5\1\3\1\6\1\7\1\2"+
    "\1\6\1\0\1\10\1\11\1\12\2\3\1\13\1\14"+
    "\1\15\1\16\1\17\1\3\1\20\1\3\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\3\1\27\1\30\3\3"+
    "\1\31\2\3\1\32\1\12\1\33\1\34\1\35\2\36"+
    "\1\37\1\40\61\0\1\3\1\0\3\3\10\0\2\3"+
    "\1\0\27\3\12\0\2\41\1\42\10\0\1\43\2\44"+
    "\42\0\3\5\10\0\1\43\42\0\7\45\1\46\1\47"+
    "\47\45\11\50\2\0\45\50\2\0\1\51\2\5\7\0"+
    "\1\12\40\0\1\12\23\0\1\52\1\53\1\0\1\54"+
    "\2\0\1\55\3\0\1\56\25\0\1\3\1\0\3\3"+
    "\10\0\2\3\1\0\1\3\1\57\13\3\1\60\11\3"+
    "\11\0\1\3\1\0\3\3\10\0\1\61\1\3\1\0"+
    "\4\3\1\62\1\63\21\3\11\0\1\3\1\0\3\3"+
    "\10\0\2\3\1\0\5\3\1\64\7\3\1\65\11\3"+
    "\11\0\1\3\1\0\3\3\10\0\2\3\1\0\2\3"+
    "\1\66\1\3\1\67\22\3\11\0\1\3\1\0\3\3"+
    "\10\0\2\3\1\0\15\3\1\70\11\3\11\0\1\3"+
    "\1\0\3\3\10\0\2\3\1\0\3\3\1\71\12\3"+
    "\1\72\2\3\1\73\1\3\1\74\3\3\11\0\1\3"+
    "\1\0\3\3\10\0\2\3\1\0\12\3\1\75\14\3"+
    "\11\0\1\3\1\0\3\3\10\0\2\3\1\0\15\3"+
    "\1\75\11\3\11\0\1\3\1\0\3\3\10\0\2\3"+
    "\1\0\4\3\1\76\22\3\11\0\1\3\1\0\3\3"+
    "\10\0\2\3\1\0\10\3\1\63\4\3\1\77\3\3"+
    "\1\100\5\3\11\0\1\3\1\0\3\3\10\0\2\3"+
    "\1\0\1\3\1\101\25\3\11\0\1\3\1\0\3\3"+
    "\10\0\2\3\1\0\24\3\1\102\2\3\11\0\1\3"+
    "\1\0\3\3\10\0\2\3\1\0\14\3\1\103\12\3"+
    "\11\0\1\3\1\0\3\3\10\0\2\3\1\0\21\3"+
    "\1\104\5\3\11\0\1\3\1\0\3\3\10\0\2\3"+
    "\1\0\15\3\1\105\11\3\61\0\1\12\3\0\1\12"+
    "\54\0\1\12\2\0\1\12\55\0\1\12\1\0\1\12"+
    "\57\0\1\12\57\0\1\12\1\36\56\0\1\12\1\0"+
    "\1\36\2\0\3\41\55\0\1\42\1\41\1\42\55\0"+
    "\3\106\56\0\3\107\52\0\7\45\1\110\1\47\47\45"+
    "\13\0\1\111\61\0\1\43\64\0\1\112\62\0\1\113"+
    "\1\114\6\0\1\115\45\0\1\116\1\0\1\117\54\0"+
    "\1\120\62\0\1\121\33\0\1\3\1\0\3\3\10\0"+
    "\2\3\1\0\2\3\1\122\24\3\11\0\1\3\1\0"+
    "\3\3\10\0\2\3\1\0\12\3\1\123\14\3\11\0"+
    "\1\3\1\0\3\3\10\0\2\3\1\0\16\3\1\124"+
    "\10\3\11\0\1\3\1\0\3\3\10\0\2\3\1\0"+
    "\12\3\1\125\14\3\11\0\1\3\1\0\3\3\10\0"+
    "\2\3\1\0\7\3\1\126\17\3\11\0\1\3\1\0"+
    "\3\3\10\0\2\3\1\0\15\3\1\127\11\3\11\0"+
    "\1\3\1\0\3\3\10\0\2\3\1\0\14\3\1\66"+
    "\12\3\11\0\1\3\1\0\3\3\10\0\2\3\1\0"+
    "\16\3\1\66\10\3\11\0\1\3\1\0\3\3\10\0"+
    "\2\3\1\0\4\3\1\130\22\3\11\0\1\3\1\0"+
    "\3\3\10\0\2\3\1\0\11\3\1\131\10\3\1\132"+
    "\4\3\11\0\1\3\1\0\3\3\10\0\2\3\1\0"+
    "\10\3\1\133\3\3\1\134\12\3\11\0\1\3\1\0"+
    "\3\3\10\0\2\3\1\0\15\3\1\135\11\3\11\0"+
    "\1\3\1\0\3\3\10\0\2\3\1\0\3\3\1\136"+
    "\23\3\11\0\1\3\1\0\3\3\10\0\2\3\1\0"+
    "\16\3\1\137\10\3\11\0\1\3\1\0\3\3\10\0"+
    "\2\3\1\0\3\3\1\140\3\3\1\141\17\3\11\0"+
    "\1\3\1\0\3\3\10\0\2\3\1\0\4\3\1\142"+
    "\22\3\11\0\1\3\1\0\3\3\10\0\2\3\1\0"+
    "\10\3\1\65\16\3\11\0\1\3\1\0\3\3\10\0"+
    "\2\3\1\0\11\3\1\143\4\3\1\144\10\3\11\0"+
    "\1\3\1\0\3\3\10\0\2\3\1\0\25\3\1\145"+
    "\1\3\11\0\1\3\1\0\3\3\10\0\2\3\1\0"+
    "\1\3\1\146\25\3\11\0\1\3\1\0\3\3\10\0"+
    "\2\3\1\0\3\3\1\147\23\3\11\0\1\3\1\0"+
    "\3\3\10\0\2\3\1\0\3\3\1\150\1\3\1\151"+
    "\21\3\12\0\4\107\75\0\1\152\55\0\1\153\62\0"+
    "\1\154\3\0\1\155\64\0\1\156\43\0\1\157\72\0"+
    "\1\160\53\0\1\161\30\0\1\3\1\0\3\3\10\0"+
    "\2\3\1\0\10\3\1\162\16\3\11\0\1\3\1\0"+
    "\3\3\10\0\2\3\1\0\17\3\1\147\7\3\11\0"+
    "\1\3\1\0\3\3\10\0\2\3\1\0\1\3\1\163"+
    "\25\3\11\0\1\3\1\0\3\3\10\0\2\3\1\0"+
    "\6\3\1\66\20\3\11\0\1\3\1\0\3\3\10\0"+
    "\2\3\1\0\1\3\1\66\25\3\11\0\1\3\1\0"+
    "\3\3\10\0\2\3\1\0\10\3\1\67\16\3\11\0"+
    "\1\3\1\0\3\3\10\0\2\3\1\0\11\3\1\66"+
    "\15\3\11\0\1\3\1\0\3\3\10\0\2\3\1\0"+
    "\4\3\1\164\22\3\11\0\1\3\1\0\3\3\10\0"+
    "\2\3\1\0\1\3\1\165\25\3\11\0\1\3\1\0"+
    "\3\3\10\0\2\3\1\0\16\3\1\166\10\3\11\0"+
    "\1\3\1\0\3\3\10\0\2\3\1\0\12\3\1\167"+
    "\14\3\11\0\1\3\1\0\3\3\10\0\2\3\1\0"+
    "\14\3\1\67\12\3\11\0\1\3\1\0\3\3\10\0"+
    "\2\3\1\0\16\3\1\170\10\3\11\0\1\3\1\0"+
    "\3\3\10\0\2\3\1\0\15\3\1\66\11\3\11\0"+
    "\1\3\1\0\3\3\10\0\2\3\1\0\15\3\1\171"+
    "\11\3\11\0\1\3\1\0\3\3\10\0\2\3\1\0"+
    "\3\3\1\172\23\3\11\0\1\3\1\0\3\3\10\0"+
    "\2\3\1\0\7\3\1\67\6\3\1\173\10\3\11\0"+
    "\1\3\1\0\3\3\10\0\2\3\1\0\3\3\1\174"+
    "\23\3\11\0\1\3\1\0\3\3\10\0\2\3\1\0"+
    "\12\3\1\163\14\3\11\0\1\3\1\0\3\3\10\0"+
    "\2\3\1\0\1\3\1\175\25\3\11\0\1\3\1\0"+
    "\3\3\10\0\2\3\1\0\10\3\1\176\16\3\11\0"+
    "\1\3\1\0\3\3\10\0\2\3\1\0\5\3\1\126"+
    "\21\3\11\0\1\3\1\0\3\3\10\0\2\3\1\0"+
    "\1\66\26\3\11\0\1\3\1\0\3\3\10\0\2\3"+
    "\1\0\10\3\1\177\16\3\34\0\1\200\57\0\1\154"+
    "\56\0\1\201\56\0\1\201\73\0\1\202\43\0\1\154"+
    "\63\0\1\203\61\0\1\204\30\0\1\3\1\0\3\3"+
    "\10\0\2\3\1\0\12\3\1\205\14\3\11\0\1\3"+
    "\1\0\3\3\10\0\2\3\1\0\14\3\1\171\12\3"+
    "\11\0\1\3\1\0\3\3\10\0\2\3\1\0\1\3"+
    "\1\150\25\3\11\0\1\3\1\0\3\3\10\0\2\3"+
    "\1\0\15\3\1\206\11\3\11\0\1\3\1\0\3\3"+
    "\10\0\2\3\1\0\3\3\1\207\23\3\11\0\1\3"+
    "\1\0\3\3\10\0\2\3\1\0\13\3\1\67\13\3"+
    "\11\0\1\3\1\0\3\3\10\0\2\3\1\0\13\3"+
    "\1\210\13\3\11\0\1\3\1\0\3\3\10\0\2\3"+
    "\1\0\4\3\1\66\22\3\11\0\1\3\1\0\3\3"+
    "\10\0\2\3\1\0\11\3\1\131\15\3\11\0\1\3"+
    "\1\0\3\3\10\0\2\3\1\0\3\3\1\211\23\3"+
    "\11\0\1\3\1\0\3\3\10\0\2\3\1\0\7\3"+
    "\1\212\17\3\11\0\1\3\1\0\3\3\10\0\2\3"+
    "\1\0\1\213\26\3\11\0\1\3\1\0\3\3\10\0"+
    "\2\3\1\0\20\3\1\66\6\3\11\0\1\3\1\0"+
    "\3\3\10\0\2\3\1\0\16\3\1\104\10\3\35\0"+
    "\1\155\67\0\1\201\55\0\1\214\55\0\1\215\27\0"+
    "\1\3\1\0\3\3\10\0\2\3\1\0\5\3\1\67"+
    "\21\3\11\0\1\3\1\0\3\3\10\0\2\3\1\0"+
    "\2\3\1\66\24\3\11\0\1\3\1\0\3\3\10\0"+
    "\2\3\1\0\13\3\1\66\13\3\11\0\1\3\1\0"+
    "\3\3\10\0\2\3\1\0\21\3\1\66\5\3\11\0"+
    "\1\3\1\0\3\3\10\0\2\3\1\0\4\3\1\216"+
    "\22\3\11\0\1\3\1\0\3\3\10\0\2\3\1\0"+
    "\16\3\1\217\10\3\11\0\1\3\1\0\3\3\10\0"+
    "\2\3\1\0\1\3\1\206\25\3\31\0\1\155\70\0"+
    "\1\155\26\0\1\3\1\0\3\3\10\0\2\3\1\0"+
    "\12\3\1\126\14\3\11\0\1\3\1\0\3\3\10\0"+
    "\2\3\1\0\1\3\1\65\25\3\10\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6384];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\3\1\1\11\3\1\1\11\30\1\3\0"+
    "\1\11\10\0\32\1\1\11\4\0\1\1\3\0\30\1"+
    "\10\0\16\1\1\0\1\11\3\0\7\1\2\0\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[143];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    private Lexema lexema(Token type) {
        return new Lexema(type, yyline, yycolumn);
    }
    private Lexema lexema(Token type, Object value) {
        return new Lexema(type, value, yyline, yycolumn);
    }
    public String token;
    public Lexema lexeme;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 190) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { lexeme= lexema(OPERADOR,yytext()); return OPERADOR;
            }
          case 13: break;
          case 2: 
            { lexeme = lexema(ERROR); return ERROR;
            }
          case 14: break;
          case 3: 
            { lexeme = lexema(IDENTIFICADOR,yytext()); return IDENTIFICADOR;
            }
          case 15: break;
          case 4: 
            { lexeme= lexema(LITERAL_ENTERO,yytext()); return LITERAL_ENTERO;
            }
          case 16: break;
          case 5: 
            { /*Ignore*/
            }
          case 17: break;
          case 6: 
            { lexeme= lexema(LITERAL_OCTAL,yytext()); return LITERAL_OCTAL;
            }
          case 18: break;
          case 7: 
            { lexeme= lexema(LITERAL_STRING,yytext()); return LITERAL_STRING;
            }
          case 19: break;
          case 8: 
            { lexeme= lexema(PALABRA_RESERVADA,yytext()); return PALABRA_RESERVADA;
            }
          case 20: break;
          case 9: 
            { lexeme= lexema(LITERAL_FLOAT,yytext()); return LITERAL_FLOAT;
            }
          case 21: break;
          case 10: 
            { lexeme= lexema(LITERAL_HEXADECIMAL,yytext()); return LITERAL_HEXADECIMAL;
            }
          case 22: break;
          case 11: 
            { lexeme= lexema(LITERAL_CARACTER,yytext()); return LITERAL_CARACTER;
            }
          case 23: break;
          case 12: 
            { lexeme= lexema(DIRECTIVA,yytext()); return DIRECTIVA;
            }
          case 24: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
